name: Upload Sourcemaps to Elastic
description: Upload generated sourcemaps to Elastic
author: Tom Varley
branding:
  icon: activity
  color: gray-dark
inputs:
  token:
    description: Elastic external access token to allow sending of sourcemaps
    required: true
  base_url:
    required: true
    description: The base url of the sourcemap you would like to associate the file with
  service_name:
    description: Service name in elastic
    required: true
  service_version:
    description: Service version in elastic
    required: true
  elastic_url:
    description: Url or Elastic instance to send sourcemap to
    required: true
  folder:
    description: Target folder to check for sourcemaps
    default: './'
runs:
  using: node16
  main: dist/index.js
