name: Action Test
on:
  workflow_dispatch:
    inputs:
      token:
        description: Elastic token
        required: true
      service_name:
        description: Service name in elastic
        required: true
      service_version:
        description: Service version in elastic
        required: true
      base_url:
        description: Base url of sourcemap
        required: true
      elastic_url:
        description: Url or Elastic instance to send sourcemap to
        required: true


jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send things
        uses: ./
        with:
          token: ${{github.event.inputs.token}}
          service_name: ${{github.event.inputs.service_name}}
          service_version: ${{github.event.inputs.service_version}}
          base_url: ${{github.event.inputs.base_url}}
          elastic_url: ${{github.event.inputs.elastic_url}}

